data:
  dt: 0.01666666753590107
  input_dir: data
  noise_std: 0.0
  num_multi_step_predictions: 10
  output_dir: results/
  test_ratio: 0.15
  train_ratio: 0.7
  val_ratio: 0.15
model:
  input_names:
  - acceleration
  - steering_rate
  neural_states:
  - 4
  - 5
  - 6
  physics_states:
  - 0
  - 1
  - 2
  - 3
  state_names:
  - delta_x
  - delta_y
  - yaw
  - steering
  - velocity
  - side_slip
  - yaw_rate
model_type: HybridODE
random_seed: 42
training:
  batch_size: 30000
  early_stopping_patience: 20
  epochs: 1000
  learning_rate: 0.001
  segment_size: 80
  validation_interval: 10
  weight_decay: 0.0001
verbose: true
